name: CI

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install base tools
        run: |
          pip install black isort flake8 pytest

      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      - name: Lint checks
        run: |
          black --check .
          isort --check-only .
          flake8 .

      - name: Run all tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Run batch ETL tests
        run: |
          pytest --maxfail=1 --disable-warnings -q tests/test_batch_etl.py
